// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"mtools-backend/config"
	"mtools-backend/database"
	"mtools-backend/handler"
	"mtools-backend/logger"
	"mtools-backend/model"
)

// Injectors from wire.go:

// BuildApp 生成注入器
func BuildApp() (*App, func(), error) {
	sugaredLogger, cleanup, err := logger.InitLogger()
	if err != nil {
		return nil, nil, err
	}
	configHandler := &handler.ConfigHandler{}
	globalConfig, err := config.InitConfig()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	engine, cleanup2, err := database.InitXormDB()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	databaseModel := &model.DatabaseModel{
		DB: engine,
	}
	databaseHandler := &handler.DatabaseHandler{
		Logger:        sugaredLogger,
		Config:        globalConfig,
		DatabaseModel: databaseModel,
	}
	coderHandler := &handler.CoderHandler{
		Logger: sugaredLogger,
		Config: globalConfig,
	}
	postmanModel := model.PostmanModel{
		DB: engine,
	}
	postmanHandler := &handler.PostmanHandler{
		PostmanModel: postmanModel,
	}
	router := &Router{
		Logger:          sugaredLogger,
		ConfigHandler:   configHandler,
		DatabaseHandler: databaseHandler,
		CoderHandler:    coderHandler,
		PostmanHandler:  postmanHandler,
	}
	app := &App{
		Router: router,
		Config: globalConfig,
		Logger: sugaredLogger,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
