// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"mtools-backend/config"
	"mtools-backend/logger"
)

// Injectors from wire.go:

// BuildApp 生成注入器
func BuildApp() (*App, func(), error) {
	sugaredLogger, cleanup, err := logger.InitLogger()
	if err != nil {
		return nil, nil, err
	}
	router := &Router{
		Logger: sugaredLogger,
	}
	globalConfig, err := config.InitConfig()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := &App{
		Router: router,
		Config: globalConfig,
		Logger: sugaredLogger,
	}
	return app, func() {
		cleanup()
	}, nil
}
